#!/bin/sh
set -e

# make folders if them doesn't exist
if [[ ! -d /config/php/php73 ]]; then
    mkdir -p /config/php/php73
fi

if [[ ! -d /config/log/php/php73 ]]; then
    mkdir -p /config/log/php/php73
fi

# create local php.ini if it doesn't exist, set local timezone
if [[ ! -f /config/php/php73/php-local.ini ]]; then
    printf "; Edit this file to override php.ini directives\\n\\ndate.timezone = %s\\n" "$TZ" >/config/php/php73/php-local.ini
fi

# symlink user php-local.ini to image
rm -rf /etc/php7/conf.d/php-local.ini
ln -s /config/php/php73/php-local.ini /etc/php7/conf.d/php-local.ini

# create override for www.conf if it doesn't exist
if [[ ! -f /config/php/php73/www2.conf ]]; then
    printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" >/config/php/php73/www2.conf
fi

# copy user www2.conf to image
rm -rf /etc/php7/php-fpm.d/www2.conf
ln -s /config/php/php73/www2.conf /etc/php7/php-fpm.d/www2.conf

# permissions
chown -R www-data:www-data \
    /config/php \
    /config/log

chown www-data:www-data \
    /config/www

# first arg is `-f` or `--some-option` or `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- php-fpm7 "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'php-fpm7' -a "$(id -u)" = '0' ]; then
    chown -R www-data .
    exec su-exec www-data "$0" "$@"
fi

exec "$@"
