name: PHP73 Docker Image Publish

on:
  workflow_dispatch:
  repository_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to AliYun Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v8
        file: Dockerfile
        context: .
        push: true
        tags: |
          clion007/docker-php73
          registry.cn-chengdu.aliyuncs.com/clion007/docker-php73
