name: PHP73 Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: clion007/docker-php73@master
    - name: Build the PHP73 Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
