name: PHP73 Docker Image Build

on:
  workflow_dispatch:
  repository_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Alicloud Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ aliyun.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Marker version and time
      id: getVersion
      run: |
        sed -i "s@COMMIT_HASH@$(git rev-parse --short HEAD)@" root/Php73
        sed -i "s@DATE_TIME@$(date +"%Y/%m/%d %H:%M")@" root/Php73
        cat root/Php73
        echo "::set-output name=time::$(date +"%Y%m%d%H%M")"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
        file: Dockerfile
        context: .
        push: true
        tags: |
          clion007/docker-php73
          registry.cn-chengdu.aliyuncs.com/clion007/docker-php73
